jobs:
  build:
    name: Java ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libs-and-reports
        path: 'build/libs

          build/reports

          '
    strategy:
      matrix:
        java:
        - 11
        - 17
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle-build.yml
